✨ Feature: S3 세팅
University-MakeUs-Challenge-ProductTeam/Official-Web-BE pull request #14
Opened 2024-10-10 12:49 UTC by yewonahn

# 💡 PR Summary - S3 세팅

### 📝 Description

---

S3 관련 세팅 및 파일 업로드 및 조회 관련 로직 구현

### 🌲 Working Branch

---

feature/#13 

### 📖 Related Issues

---

#13 

### 📚 Etc

---

2024-10-28 15:21 UTC, catturtle123 requested changes

2024-10-28 15:21 UTC, catturtle123 commented on src/main/java/umc/product/web/global/s3/controller/S3Controller.java
> +    @GetMapping("/presigned/upload")
Get일 시 RequestBody를 받지 못합니다.

2024-10-28 15:21 UTC, catturtle123 commented on src/main/java/umc/product/web/global/s3/controller/S3Controller.java
> +    @GetMapping("/presigned/upload/files")
위와 같습니다.

2024-11-02 16:33 UTC, yewonahn commented on src/main/java/umc/product/web/global/s3/controller/S3Controller.java
> +    @GetMapping("/presigned/upload")
수정하였습니다..

2024-11-02 16:51 UTC, catturtle123 approved these changes

2024-11-02 16:52 UTC, merged